import type { Move, Opponent } from './types';

export const ALL_MOVES: Move[] = [
  {
    id: 'bodegas',
    name: 'Bodegas Platform',
    type: 'FULLSTACK',
    power: 80,
    pp: 5,
    maxPp: 5,
    followUpVulnerable: true,
    proven: true,
  },
  { id: 'barbershop', name: 'Barber Shop System', type: 'DATABASE', power: 70, pp: 5, maxPp: 5 },
  {
    id: 'enterprise-backend',
    name: 'Enterprise Backend',
    type: 'BACKEND',
    power: 75,
    pp: 4,
    maxPp: 4,
    proven: true,
  },
  { id: 'trash-api', name: 'Trash Detection API', type: 'AI', power: 65, pp: 5, maxPp: 5 },
  {
    id: 'food-graph',
    name: 'Food Recommendation Graph',
    type: 'ARCHITECTURE',
    power: 60,
    pp: 5,
    maxPp: 5,
  },
  {
    id: 'lisp-interpreter',
    name: 'Lisp Interpreter',
    type: 'ALGORITHMS',
    power: 85,
    pp: 3,
    maxPp: 3,
  },
  { id: 'http-go', name: 'HTTP Server in Go', type: 'ALGORITHMS', power: 55, pp: 5, maxPp: 5 },
  {
    id: 'typescript-mastery',
    name: 'TypeScript Strict',
    type: 'FULLSTACK',
    power: 60,
    pp: 10,
    maxPp: 10,
  },
  { id: 'docker', name: 'Docker Compose Stack', type: 'DEVOPS', power: 65, pp: 8, maxPp: 8 },
  { id: 'react-3d', name: 'React Three Fiber', type: 'FRONTEND', power: 70, pp: 5, maxPp: 5 },
  {
    id: 'ta-algorithms',
    name: 'TA: Algorithms & DS',
    type: 'TEACHING',
    power: 0,
    pp: 3,
    maxPp: 3,
    status: true,
  },
  {
    id: 'ta-microprocessors',
    name: 'TA: Microprocessors',
    type: 'TEACHING',
    power: 0,
    pp: 3,
    maxPp: 3,
    status: true,
    badgeUnlock: 'TEACHING',
  },
];

export const OPPONENTS: Opponent[] = [
  {
    id: 'alex',
    name: 'ALEX "The Checklist"',
    level: 12,
    hp: 80,
    typeTag: 'JUNIOR',
    moves: [
      { id: 'q1', type: 'THEORY', power: 30 },
      { id: 'q2', type: 'EXPERIENCE', power: 20 },
      { id: 'q3', type: 'THEORY', power: 25 },
      { id: 'q4', type: 'PROJECT', power: 35 },
    ],
  },
  {
    id: 'diana',
    name: 'DIANA "Deep Dive"',
    level: 28,
    hp: 140,
    typeTag: 'MID',
    followUp: true,
    moves: [
      { id: 'd1', type: 'DATABASE', power: 55 },
      { id: 'd2', type: 'DATABASE', power: 60 },
      { id: 'd3', type: 'DEVOPS', power: 58 },
      { id: 'd4', type: 'SYSTEM-DESIGN', power: 70 },
    ],
  },
  {
    id: 'rafael',
    name: 'RAFAEL "The Socratic"',
    level: 52,
    hp: 200,
    typeTag: 'SENIOR',
    socratic: true,
    moves: [
      { id: 'r1', type: 'ALGORITHMS', power: 75 },
      { id: 'r2', type: 'SYSTEM-DESIGN', power: 80 },
      { id: 'r3', type: 'SYSTEM-DESIGN', power: 85 },
      { id: 'r4', type: 'ALGORITHMS', power: 90 },
    ],
  },
];

export const EFFECTIVENESS: Record<string, Record<string, number>> = {
  JUNIOR: {
    FULLSTACK: 2,
    FRONTEND: 2,
    BACKEND: 1.5,
    DATABASE: 1,
    DEVOPS: 1,
    MOBILE: 1.5,
    ALGORITHMS: 0.5,
    ARCHITECTURE: 0.5,
    TEACHING: 1,
    EXPERIENCE: 2,
    AI: 1,
  },
  MID: {
    FULLSTACK: 1,
    FRONTEND: 0.5,
    BACKEND: 1,
    DATABASE: 2,
    DEVOPS: 2,
    MOBILE: 1,
    ALGORITHMS: 1,
    ARCHITECTURE: 2,
    TEACHING: 1.5,
    EXPERIENCE: 1.5,
    AI: 1.5,
  },
  SENIOR: {
    FULLSTACK: 0.5,
    FRONTEND: 0.25,
    BACKEND: 0.5,
    DATABASE: 1,
    DEVOPS: 1,
    MOBILE: 0.5,
    ALGORITHMS: 2,
    ARCHITECTURE: 1.5,
    TEACHING: 2,
    EXPERIENCE: 1,
    AI: 1.5,
  },
};
